fn main() {
    windows::build!(
        Windows::Win32::Security::{
            TOKEN_STATISTICS,
            OpenProcessToken,
            GetTokenInformation,
            DuplicateTokenEx,
            SetThreadToken,
            BCryptGenerateSymmetricKey,
            BCryptOpenAlgorithmProvider,
            BCryptGetProperty,
            BCryptSetProperty,
            BCryptEncrypt,
            BCryptDecrypt,
            ConvertSidToStringSidA,
            SID,
            UNICODE_STRING,
        },
        Windows::Win32::SystemServices::{
            CreateProcessWithLogonW,
            TerminateProcess,
            ResumeThread,
            OpenProcess,
            GetProcessId,
            NtQueryInformationProcess,
            LocalFree,
            PEB_LDR_DATA,
            PEB,
            PWSTR,
            PROCESS_ACCESS_RIGHTS,
        },
        Windows::Win32::WindowsProgramming::{
            FILETIME,
            CloseHandle,
            LDR_DATA_TABLE_ENTRY,
            PROCESS_BASIC_INFORMATION,
        },
        Windows::Win32::Debug::{
            ReadProcessMemory,
            WriteProcessMemory,
            GetLastError,
        },
        Windows::Win32::Kernel::{
            LIST_ENTRY,
            LUID,
        },
    );
}
